export const AI_RATE_LIMIT_MAX_REQUESTS = 20;
export const AI_RATE_LIMIT_WINDOW = "1 h" as const;
export const AUTO_TAG_CONTENT_LIMIT = 2_000;
export const AUTO_TAG_MAX_SUGGESTIONS = 5;
export const EXPLAIN_CODE_CONTENT_LIMIT = 12_000;
export const OPTIMIZE_PROMPT_CONTENT_LIMIT = 12_000;
